app/models/reminder.py
import datetime
import random

from app import db

class Reminder(db.Model):
    __tablename__ = 'reminders'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, index=True)
    content = db.Column(db.String, index=True)
    date = db.Column(db.Date, index=True)
    time = db.Column(db.Time, index=True)
    sent = db.Column(db.Boolean, index=True, default=False)

    def format_date(self):
        return self.date.strftime('%M/%D/%Y')

    def format_time(self):
        return self.time.strftime('%-I:%M %p')

    @staticmethod
    def generate_fake(count=3):
        for i in range(1, count + 1):
            # randomly generate a reminder datetime to be within 1-3 minutes from now
            soon = datetime.datetime.now() + datetime.timedelta(
                seconds=random.randint(60, 180))
            reminder = Reminder(
                title=f'Reminder {i}',
                content=f'Please make sure to complete Task #{i}.',
                date=soon.date(),
                time=soon.time())
            db.session.add(reminder)
            try:
                db.session.commit()
            except:
                db.session.rollback()

app/reminder/forms.py
import itertools

from flask_wtf import FlaskForm
from wtforms.fields import SelectField, StringField, SubmitField, TextAreaField
from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired, Length


class SendNewReminderForm(FlaskForm):
    title = StringField(
        'Reminder title',
        validators=[InputRequired(), Length(1, 64)]
    )
    content = TextAreaField(
        'Content',
        validators=[InputRequired()]
    )
    submit = SubmitField('Send Now')


class SendNewReminderForm(FlaskForm):
    title = StringField(
        'Reminder title',
        validators=[InputRequired(), Length(1, 64)]
    )
    content = TextAreaField(
        'Content',
        validators=[InputRequired()]
    )
    submit = SubmitField('Send Now')


class ScheduleNewReminderForm(FlaskForm):
    title = StringField(
        'Reminder title', validators=[InputRequired(),
                                      Length(1, 64)])
    content = TextAreaField('Content', validators=[InputRequired()])
    date = DateField('Date', format='%Y-%m-%d', validators=[InputRequired()])
    hours = ['12'] + [str(x) for x in range(1, 12)]
    time = SelectField(
        'Time',
        choices=[(f'{h} AM', f'{h} AM') for h in hours] +
                [(f'{h} PM', f'{h} PM') for h in hours],
        validators=[InputRequired()]
    )
    submit = SubmitField('Schedule Reminder')

app/admin/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.admin.forms import (
    ChangeAccountTypeForm,
    ChangeUserEmailForm,
    InviteUserForm,
    NewUserForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import EditableHTML, Role, User

admin = Blueprint('admin', __name__)


@admin.route('/')
@login_required
@admin_required
def index():
    """Admin dashboard page."""
    return render_template('admin/index.html')


@admin.route('/new-user', methods=['GET', 'POST'])
@login_required
@admin_required
def new_user():
    """Create a new user."""
    form = NewUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully created'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/invite-user', methods=['GET', 'POST'])
@login_required
@admin_required
def invite_user():
    """Invites a new user to create an account and set their own password."""
    form = InviteUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        invite_link = url_for(
            'account.join_from_invite',
            user_id=user.id,
            token=token,
            _external=True)
        get_queue().enqueue(
            send_email,
            recipient=user.email,
            subject='You Are Invited To Join',
            template='account/email/invite',
            user=user,
            invite_link=invite_link,
        )
        flash('User {} successfully invited'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/users')
@login_required
@admin_required
def registered_users():
    """View all registered users."""
    users = User.query.all()
    roles = Role.query.all()
    return render_template(
        'admin/registered_users.html', users=users, roles=roles)


@admin.route('/user/<int:user_id>')
@admin.route('/user/<int:user_id>/info')
@login_required
@admin_required
def user_info(user_id):
    """View a user's profile."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/change-email', methods=['GET', 'POST'])
@login_required
@admin_required
def change_user_email(user_id):
    """Change a user's email."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    form = ChangeUserEmailForm()
    if form.validate_on_submit():
        user.email = form.email.data
        db.session.add(user)
        db.session.commit()
        flash('Email for user {} successfully changed to {}.'.format(
            user.full_name(), user.email), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route(
    '/user/<int:user_id>/change-account-type', methods=['GET', 'POST'])
@login_required
@admin_required
def change_account_type(user_id):
    """Change a user's account type."""
    if current_user.id == user_id:
        flash('You cannot change the type of your own account. Please ask '
              'another administrator to do this.', 'error')
        return redirect(url_for('admin.user_info', user_id=user_id))

    user = User.query.get(user_id)
    if user is None:
        abort(404)
    form = ChangeAccountTypeForm()
    if form.validate_on_submit():
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('Role for user {} successfully changed to {}.'.format(
            user.full_name(), user.role.name), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route('/user/<int:user_id>/delete')
@login_required
@admin_required
def delete_user_request(user_id):
    """Request deletion of a user's account."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/_delete')
@login_required
@admin_required
def delete_user(user_id):
    """Delete a user's account."""
    if current_user.id == user_id:
        flash('You cannot delete your own account. Please ask another '
              'administrator to do this.', 'error')
    else:
        user = User.query.filter_by(id=user_id).first()
        db.session.delete(user)
        db.session.commit()
        flash('Successfully deleted user %s.' % user.full_name(), 'success')
    return redirect(url_for('admin.registered_users'))


@admin.route('/_update_editor_contents', methods=['POST'])
@login_required
@admin_required
def update_editor_contents():
    """Update the contents of an editor."""

    edit_data = request.form.get('edit_data')
    editor_name = request.form.get('editor_name')

    editor_contents = EditableHTML.query.filter_by(
        editor_name=editor_name).first()
    if editor_contents is None:
        editor_contents = EditableHTML(editor_name=editor_name)
    editor_contents.value = edit_data

    db.session.add(editor_contents)
    db.session.commit()

    return 'OK', 200

app/reminder/__init__.py
from app.reminder.views import reminder  # noqa

app/reminder/views.py
import datetime

from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)

from flask_login import login_required
from sqlalchemy.exc import IntegrityError

from app.decorators import *

from app import db
from app.models import Reminder
from app.sms import send
from app.email import send_email
from app.reminder.forms import ScheduleNewReminderForm, SendNewReminderForm

reminder = Blueprint('reminder', __name__)


@reminder.route('/', methods=['GET'])
@login_required
def dashboard():
    """Dashboard to view and add text and email reminders."""
    return render_template(
        'reminder/index.html', reminders=Reminder.query.all())

@reminder.route('/send', methods=['GET', 'POST'])
def send_new_reminder_form():
    """Create a new reminder and send it immediately."""
    form = SendNewReminderForm()
    if form.validate_on_submit():
        now = datetime.datetime.now()
        reminder = Reminder(
            title=form.title.data,
            content=form.content.data,
            date=now.date(),
            time=now.time(),
            sent=True
        )
        db.session.add(reminder)
        try:  # TODO: Add flashes
            db.session.commit()
            send(reminder)
            return redirect(url_for('reminder.dashboard'))
        except IntegrityError:
            db.session.rollback()
    return render_template('reminder/send_form.html', form=form)


@reminder.route('/schedule', methods=['GET', 'POST'])
def schedule_new_reminder_form():
    """Create a new reminder and schedule it for later."""
    form = ScheduleNewReminderForm()
    if form.validate_on_submit():
        hour, am_pm = form.time.data.split(' ', 1)
        hour = (int(hour) % 12) + (12 if am_pm.lower() == 'pm' else 0)
        reminder = Reminder(
            title=form.title.data,
            content=form.content.data,
            date=form.date.data,
            time=datetime.time(hour=hour))
        db.session.add(reminder)
        try:  # TODO: Add flashes
            db.session.commit()
            return redirect(url_for('reminder.dashboard'))
        except IntegrityError:
            db.session.rollback()
    return render_template('reminder/schedule_form.html', form=form)

app/templates/reminder/index.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
<div class="ui stackable grid container">
    <div class="sixteen wide tablet twelve wide computer centered column">
        <a class="ui basic compact button" href="{{ url_for('admin.index') }}">
            <i class="caret left icon"></i>
            Back to dashboard
        </a>
        <h2 class="ui header">
            Manage Reminders
            <div class="sub header">
                View and modify text/email reminders.
            </div>
        </h2>

        <div class="ui fluid icon input">
            <input id="search-alerts" type="text" placeholder="Search...">
            <i class="search icon"></i>
        </div>

        <table class="ui searchable unstackable selectable celled table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Date/Time</th>
                </tr>
            </thead>
            <tbody>
            {% for r in reminders %}
            <tr>
                <td>{{ r.title }}</td>
                <td>{{ r.content }}</td>
                <td>{{ r.format_date() }} {{ r.format_time() }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ url_for('reminder.send_new_reminder_form') }}" class="ui black button">Send New Reminder</a>
        <a href="{{ url_for('reminder.schedule_new_reminder_form') }}" class="ui button">Schedule Reminder for Later</a>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#search-alerts').keyup(function () {
            var searchText = $(this).val();
            if (searchText.length > 0) {
                $('tbody td:icontains(' + searchText + ')').addClass('positive');
                $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
            } else {
                $('td.positive').removeClass('positive');
                $('tr.hidden').removeClass('hidden').show();
            }
        });
    });
</script>

{% endblock %}

app/templates/reminder/schedule_form.html
{% import 'macros/page_macros.html' as page %}
{% import 'macros/form_macros.html' as f %}
{% extends 'layouts/base.html' %}

{% block content %}
<div class="ui stackable grid container">
    <div class="sixteen wide tablet twelve wide computer centered column">
        <br />
        <a class="ui basic compact button" href="{{ url_for('reminder.dashboard') }}">
            <i class="caret left icon"></i>
            Back to all reminders
        </a>
        <h1>Add New Reminder</h1>

        {{ f.render_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/reminder/send_form.html
{% import 'macros/page_macros.html' as page %}
{% import 'macros/form_macros.html' as f %}
{% extends 'layouts/base.html' %}

{% block content %}
<div class="ui stackable grid container">
    <div class="sixteen wide tablet twelve wide computer centered column">
        <br />
        <a class="ui basic compact button" href="{{ url_for('reminder.dashboard') }}">
            <i class="caret left icon"></i>
            Back to all reminders
        </a>
        <h1>Add New Reminder</h1>

        {{ f.render_form(form) }}
    </div>
</div>
{% endblock %}